[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"
